CREATE TABLE Income (
    
    SA2_code INTEGER PRIMARY KEY,
    SA2_Name VARCHAR(255),
    Earners INTEGER,
    Median_age INTEGER,
    Median_income INTEGER,
    Mean_income INTEGER,
);
CREATE TABLE Population (
    SA2_code INTEGER PRIMARY KEY,
    SA2_Name VARCHAR(255),
    0_4_People INTEGER,
    5_9_People INTEGER,
    10_14_People INTEGER,
    15_19_People INTEGER,
    20_24_People INTEGER,
    25_29_People INTEGER,
    30_34_People INTEGER,
    35_39_People INTEGER,
    40_44_People INTEGER,
    45_49_People INTEGER,
    50_54_People INTEGER,
    55_59_People INTEGER,
    60_64_People INTEGER,
    65_69_People INTEGER,
    70_74_People INTEGER,
    75_79_People INTEGER,
    80_84_People INTEGER,
    85_Over INTEGER,
    Total_people INTEGER,
    FOREIGN KEY (SA2_code) REFERENCES Income(SA2_code)
);
CREATE TABLE Businesses (
    Industry_code VARCHAR(255),
    Industry_name VARCHAR(255),
    SA2_code INTEGER PRIMARY KEY,
    SA2_name VARCHAR(255),
    0_to_50k_businesses INTEGER,
    50k_to_200k_businesses INTEGER,
    200k_to_2m_businesses INTEGER,
    2m_to_5m_businesses INTEGER,
    5m_to_10m_businesses INTEGER,
    10m_or_more_businesses INTEGER,
    Total_businesses INTEGER,
    FOREIGN KEY (SA2_code)
);
CREATE TABLE PollingPlaces (
    FID VARCHAR(255),
    State_ VARCHAR(255),
    Division_name VARCHAR(255),
    Division_id INTEGER,
    Polling_place_type_id INTEGER,
    Polling_place_name VARCHAR(255),
    Premises_name VARCHAR(255),
    Premises_address_1 VARCHAR(255),
    Premises_address_2 VARCHAR(255),
    Premises_address_3 VARCHAR(255),
    Premises_suburb VARCHAR(255),
    Premises_state_abbreviation VARCHAR(255),
    Premises_postal_code INTEGER,
    Latitude INTEGER,
    Longitude INTEGER,
    The_geom INTEGER,
    FOREIGN KEY (SA2_ID) REFERENCES SA2_Regions(SA2_ID)
),

CREATE TABLE Stops (
Stop_id INTEGER,
Stop_code INTEGER,
Stop_name VARCHAR(255),
Stop_lat double,
Stop_lon Doub;e ,
Location_type VARCHAR(255),
Parent_station VARCHAR(255),
Wheelchair_boarding INTEGER,
Platform_code INTEGER,
),