CREATE TABLE Income (
    
    SA2code INTEGER PRIMARY KEY,
    SA2name VARCHAR(255),
    Earners INTEGER,
    MedianAge INTEGER,
    MedianIncome INTEGER,
    MeanIncome INTEGER,
);
CREATE TABLE Population (
    SA2code INTEGER PRIMARY KEY,
    SA2name VARCHAR(255),
    0to4 INTEGER,
    5to9 INTEGER,
    10to14 INTEGER,
    15to19 INTEGER,
    20to24 INTEGER,
    25to29 INTEGER,
    30to34 INTEGER,
    35to39 INTEGER,
    40to44 INTEGER,
    45to49 INTEGER,
    50to54 INTEGER,
    55to59 INTEGER,
    60to64 INTEGER,
    65to69 INTEGER,
    70to74 INTEGER,
    75to79 INTEGER,
    80to84 INTEGER,
    85Over INTEGER,
    TotalPeople INTEGER,
    -- FOREIGN KEY (SA2code) REFERENCES Income(SA2code)
);
CREATE TABLE Businesses (
    IndustryCode VARCHAR(255),
    IndustryName VARCHAR(255),
    SA2code INTEGER PRIMARY KEY,
    SA2name VARCHAR(255),
    0kto50k INTEGER,
    50kto200k INTEGER,
    200kto2M INTEGER,
    2Mto5M INTEGER,
    5Mto10M INTEGER,
    10MOver INTEGER,
    TotalBusinesses INTEGER,
    FOREIGN KEY (SA2code)
);
CREATE TABLE PollingPlaces (
    -- Check the column names with CSV
    FID VARCHAR(255) PRIMARY KEY,
    DivisionName VARCHAR(255),
    DivisionID INTEGER,
    PlaceID INTEGER,
    TypeID INTEGER,
    PlaceName VARCHAR(255),
    PremisesName VARCHAR(255),
    Address1 VARCHAR(255),
    Address2 VARCHAR(255),
    Address3 VARCHAR(255),
    Suburb VARCHAR(255),
    StateABV VARCHAR(255),
    Postcode INTEGER,
    Latitude NUMERIC,
    Longitude NUMERIC,
    Geom GEOMETRY(POINT,4326),
    -- FOREIGN KEY (SA2_ID) REFERENCES SA2_Regions(SA2_ID)
);

CREATE TABLE Stops (
    StopID INTEGER,
    StopCode INTEGER,
    StopName VARCHAR(255),
    LocationType VARCHAR(255),
    ParentStation VARCHAR(255),
    WheelchairBoarding INTEGER,
    PlatformCode INTEGER
    geom GEOMETRY(POINT,4326)
);

CREATE TABLE Primary (
    USE_ID INTEGER PRIMARY KEY,
    Catch_type VARCHAR (255),
    Use_desc VARCHAR(255),
    Add_date INTEGER,
    Kindergarten VARCHAR,
    Year1 VARCHAR,
    Year2 VARCHAR,
    Year3 VARCHAR,
    Year4 VARCHAR,
    Year5 VARCHAR,
    Year6 VARCHAR,
    Year7 VARCHAR,
    Year8 VARCHAR,
    Year9 VARCHAR,
    Year10 VARCHAR,
    Year11 VARCHAR,
    Year12 VARCHAR,
);

CREATE TABLE Secondary (
    USE_ID INTEGER PRIMARY KEY,
    Catch_type VARCHAR (255),
    Use_desc VARCHAR(255),
    Add_date INTEGER,
    Kindergarten VARCHAR,
    Year1 VARCHAR,
    Year2 VARCHAR,
    Year3 VARCHAR,
    Year4 VARCHAR,
    Year5 VARCHAR,
    Year6 VARCHAR,
    Year7 VARCHAR,
    Year8 VARCHAR,
    Year9 VARCHAR,
    Year10 VARCHAR,
    Year11 VARCHAR,
    Year12 VARCHAR,
);

CREATE TABLE Future (
    USE_ID INTEGER PRIMARY KEY,
    Catch_type VARCHAR (255),
    Use_desc VARCHAR(255),
    Add_date INTEGER,
    Kindergarten VARCHAR,
    Year1 INTEGER,
    Year2 INTEGER,
    Year3 INTEGER,
    Year4 INTEGER,
    Year5 INTEGER,
    Year6 INTEGER,
    Year7 INTEGER,
    Year8 INTEGER,
    Year9 INTEGER,
    Year10 INTEGER,
    Year11 INTEGER,
    Year12 INTEGER,
);
CREATE TABLE SA2 (
    SA2_CODE INTEGER,
    SA2_NAME21 VARCHAR,
    CHG_FLAG21 INTEGER,
    CHG_LBL21 VARCHAR,
    SA3_CODE21 INTEGER,
    SA3_NAME21 VARCHAR,
    SA4_CODE21 INTEGER,
    SA4_NAME21 VARCHAR,
    GCC_CODE21 VARCHAR,
    GCC_NAME21 VARCHAR,
    STE_CODE21 INTEGER,
    STE_NAME21 VARCHAR,
    AUS_CODE21 VARCHAR,
    AUS_NAME21 VARCHAR,
    AREASQKM21 FLOAT
);